import type { NextPage } from 'next'
import Head from 'next/head'
import { useSession } from "next-auth/react"

const Home: NextPage = () => {
  const session = useSession()
  return (
    <>
      <Head>
        <title>AirUi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session && 
      <main>
        <h1> Welcome {session.data?.user?.name} to AirUi </h1>
      </main>}
    </>
  );
}

export default Home
